package ltudjava.pkg18hcb.mssv.bt2;
// Generated Aug 25, 2019 9:35:51 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private String stt;
     private String mssv;
     private String hoTen;
     private String diemGk;
     private String diemCk;
     private String diemKhac;
     private String diemTong;

    public Diem() {
    }

    public Diem(String stt, String mssv, String hoTen, String diemGk, String diemCk, String diemKhac, String diemTong) {
       this.stt = stt;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public String getStt() {
        return this.stt;
    }
    
    public void setStt(String stt) {
        this.stt = stt;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(String diemGk) {
        this.diemGk = diemGk;
    }
    public String getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(String diemCk) {
        this.diemCk = diemCk;
    }
    public String getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(String diemKhac) {
        this.diemKhac = diemKhac;
    }
    public String getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(String diemTong) {
        this.diemTong = diemTong;
    }




}


