package ltudjava.pkg18hcb.mssv.bt2;
// Generated Aug 25, 2019 9:35:51 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String stt;
     private String mssv;
     private String hoTen;
     private String gioiTinh;
     private String cmnd;

    public Sinhvien() {
    }

    public Sinhvien(String stt, String mssv, String hoTen, String gioiTinh, String cmnd) {
       this.stt = stt;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
    }
   
    public String getStt() {
        return this.stt;
    }
    
    public void setStt(String stt) {
        this.stt = stt;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }




}


