package ltudjava.pkg18hcb.mssv.bt2;
// Generated Aug 25, 2019 9:35:51 PM by Hibernate Tools 4.3.1



/**
 * Thoikhoabieu generated by hbm2java
 */
public class Thoikhoabieu  implements java.io.Serializable {


     private int stt;
     private int maMon;
     private int tenMon;
     private int phongHoc;

    public Thoikhoabieu() {
    }

    public Thoikhoabieu(int stt, int maMon, int tenMon, int phongHoc) {
       this.stt = stt;
       this.maMon = maMon;
       this.tenMon = tenMon;
       this.phongHoc = phongHoc;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public int getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(int maMon) {
        this.maMon = maMon;
    }
    public int getTenMon() {
        return this.tenMon;
    }
    
    public void setTenMon(int tenMon) {
        this.tenMon = tenMon;
    }
    public int getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(int phongHoc) {
        this.phongHoc = phongHoc;
    }




}


